export const INSULTS = [
    'attarde',
    'putain de merde',
    'nique ta mère',
    'fils de chien',
    'chienne',
    'fils de pute',
    'va te faire foutre',
    'va te faire',
    'trou du cul',
    'sac à merde',
    'sale bâtard',
    'gros suceur',
    'pouffiasse',
    'homophobe',
    'ta gueule',
    'saloperie',
    'gros porc',
    'connerie',
    'bullshit',
    'salopard',
    'zoophile',
    'connasse',
    'tarlouze',
    'imbécile',
    'connard',
    'branleur',
    'branle',
    'java',
    'raciste',
    'bouffon',
    'pétasse',
    'baiseur',
    'salope',
    'putain',
    'enculé',
    'bordel',
    'foutre',
    'bâtard',
    'gogole',
    'suceur',
    'foutre',
    'ordure',
    'merde',
    'putin',
    'nique',
    'sucer',
    'clodo',
    'pute',
    'nazi',
    'chié',
    'fion',
    'taré',
    'cul',
    'bite',
    'penis',
    'ptn',
    'fdp',
    'ntm',
    'pd',
    'tg'
];